Update and add readme

diff --git a/aweb b/aweb
--- a/aweb
+++ b/aweb
@@ -1,48 +1,33 @@
 #!/bin/sh
-# aweb v0.1; copyright 2021 Job79
-# license: mit-license.org
-HELP(){ printf "USAGE
-	aweb command [args...]
-
-COMMANDS
-	run [filter]		Generate changed files
-	crun [filter]		Clean and generate files
-	clean			Remove generated website files
-"; }
+HELP(){ echo "AWEB V1; made by Job79
+run [filter]	generate changed files
+clean		delete generated files";}
 RUN(){
-	[ -x 'config' ] && . './config'
-	$(find 'src' -type f \( -name "${2:-*}" ! -path '*_*' \) | while read -r in
-	do
+	(find 'src' -type f \( -path "*$1" ! -path '*_*' \) | while read -r in; do
 		out="out/${in#*/}"
-		if [ -n "$2" ] || [ ! -f "$out" ] || [ "$( find "$in" -newer "$out" )" ]; then
-			log "$in" 'run'
+		if [ -n "$1" ] || [ ! -f "$out" ] || [ "$in" -nt "$out" ]; then
+			(log "$in" 'run'
 			outdir="${out%/*}"; [ ! -d "$outdir" ] && mkdir -p "$outdir"
-			if [ -x "$in" ]; then . "./$in" > "$out"; else cp "$in" "$out"; fi
-			(for h in $hooks; do ${h#*:} >&2; done)&
+			if [ -x "$in" ]; then . "./$in" >"$out"; else cp "$in" "$out"; fi
+			for h in $hooks; do ${h#*:}; done)&
 		fi
-	done)
-	[ -x 'publish' ] && . './publish'
+	done) | cat
 }
-CLEAN(){ log 'cleaned output folder'; rm -rf out; }
 
-# LIB #
-use(){ for p in "$@"; do [ -x "mod/$p" ] || continue; debug "loading module $p"; . "./mod/$p"; done }
+use(){ for p in "$@"; do [ -x "mod/$p" ] || continue; debug "loading module $p"; . "./mod/$p"; done; }
 hook(){ debug "registering hook $1:$2"; hooks="$(printf '%s\n' $hooks "$1:$2" | sort -n | tr '\n' ' ')"; }
-include(){ [ -f "src/$1" ] && . "./src/$1"; }
-
-log(){ printf '\e[0;35m[\e[0m%s\e[0;35m]\e[0m %s\n' "${2:-info}" "$1" >&2; }
-warning() { printf '[\e[0;33m%s\e[0m] %s\n' "${2:-warning}" "$1" >&2; }
-error() { printf '[\e[0;31m%s\e[0m] %s\n' "${2:-error}" "$1" >&2; }
-debug(){ [ "$debug" = '1' ] && printf '\e[0;33m[\e[0m%s\e[0;33m]\e[0m %s\n' "${2:-debug}" "$1" >&2; }
-
+include(){ [ -x "src/$1" ] && . "./src/$1"; }
+log(){ printf '\e[0;%sm[\e[0m%s\e[0;%sm]\e[0m %s\n' "${3:-35}" "${2:-info}" "${3:-35}" "$1"; }
+warn(){ log "$1" "${2:-warning}" 33; }
+err(){ log "$1" "${2:-error}" 31; exit 1; }
+debug(){ [ "$debug" = '1' ] && log "$1" "${2:-debug}"; }
 alias _='cat<<\_'; alias __='cat<<__'
 
-# RUN #
-cd "$(dirname "$(realpath "$0")")" || exit;
-debug='0'; PATH="./bin:$PATH"; exec 2>&1
+cd "$(dirname "$(realpath "$0")")" || exit
+PATH="./bin:$PATH"
+[ -x 'config' ] && . './config'
 case "$1" in
-	run) RUN "$@" ;;
-	crun) CLEAN; RUN "$@" ;;
-	clean) CLEAN ;;
+	run) RUN "$2" ;;
+	clean) rm -rf out ;;
 	*) HELP ;;
-esac; exit 0
+esac
diff --git a/mod/compression/brotli b/mod/compression/brotli
--- a/mod/compression/brotli
+++ b/mod/compression/brotli
@@ -1,23 +1,14 @@
 #!/bin/sh
 # create brotli compressed versions of website files
-#
-# USAGE [ hook ]
-#	install brotli and invoke this module
-#
-# VARIABLES
-#	brotli_compression_level; default: 9
-#		the used brotli compression level
-#	compression_filter; default: html|css|js
-#		list of targeted filetypes
 if ! command -v brotli >/dev/null 2>&1; then
-	warning 'could not find brotli' 'brotli'
+	warn 'could not find brotli' 'brotli'
 	return
 fi
 
 hook '9' 'hook_brotli'
 hook_brotli() {
 	brotli_compression_level="${brotli_compression_level:-9}"
-	echo "${out##*.}" | grep -Eq "^(${compression_filter:-html|css|js})$" || return
+	echo "${out##*.}" | grep -Eq "^(${compression_filter:-html|css|js|svg})$" || return
 	debug "compressing $out; level: $brotli_compression_level" 'brotli'
 	brotli "-kf$brotli_compression_level" "$out"
 }
diff --git a/mod/compression/gzip b/mod/compression/gzip
--- a/mod/compression/gzip
+++ b/mod/compression/gzip
@@ -1,23 +1,14 @@
 #!/bin/sh
 # create gzip compressed versions of website files
-#
-# USAGE [ hook ]
-#	install gzip and invoke this module
-#
-# VARIABLES
-#	gzip_compression_level; default: 9
-#		the used gzip compression level
-#	compression_filter; default: html|css|js
-#		list of targeted filetypes
 if ! command -v gzip >/dev/null 2>&1; then
-	warning 'could not find gzip' 'gzip'
+	warn 'could not find gzip' 'gzip'
 	return
 fi
 
 hook '9' 'hook_gzip'
 hook_gzip() {
 	gzip_compression_level="${gzip_compression_level:-9}"
-	echo "${out##*.}" | grep -Eq "^(${compression_filter:-html|css|js})$" || return
+	echo "${out##*.}" | grep -Eq "^(${compression_filter:-html|css|js|svg})$" || return
 	debug "compressing $out; level: $gzip_compression_level" 'gzip'
 	gzip "-kf$gzip_compression_level" "$out"
 }
diff --git a/mod/templates b/mod/templates
--- a/mod/templates
+++ b/mod/templates
@@ -1,22 +1,12 @@
 #!/bin/sh
-# add template (default layout) support to aweb
-#
-# USAGE [ hook ]
-#	create a layout script and invoke this module
-#	the layout page should output the content variable
-#
-# VARIABLES
-#	template
-#		flags for the minify application
-#	template_filter; default: html
-#		list of targeted filetypes
+# add template support to aweb
 hook '5' 'hook_templates'
-hook_templates() {(
+hook_templates(){
 	template="${template:-_layout.html}"
-	[ ! -x "src/$template" ] && warning "template file not found; missing: $template" 'templates' && return
+	[ -x "src/$template" ] || err "template file not found; missing: $template" 'templates'
 	echo "${out##*.}" | grep -Eq "^(${template_filter:-html})$" || return
-
 	debug "applying $template to $out" 'templates'
 	content="$(cat "$out")"
 	. "./src/$template" > "$out"
-)}
+	unset content
+}
