refactor: pre-release aweb 3

diff --git a/mod/compression/brotli b/mod/compression/brotli
--- a/mod/compression/brotli
+++ b/mod/compression/brotli
@@ -1,14 +1,21 @@
 #!/bin/sh
-# brotli compress website files
+# brotli compresses website files
+#
+# PARAMS
+# $compression_filter list with extensions that should be compressed
+# $brotli_compression_level compression level
 if ! command -v brotli >/dev/null 2>&1; then
-	warn 'could not find brotli' 'brotli'
+	err 'could not find brotli binary' 'brotli'
 	return
 fi
 
-hook 9 'hook_brotli'
+hook 'hook_brotli'
 hook_brotli() {
-	brotli_compression_level="${brotli_compression_level:-Z}"
-	echo "${out##*.}" | grep -Eq "^(${compression_filter:-html|css|js|svg|ico|atom})$" || return
-	debug "compressing $out; level: $brotli_compression_level" 'brotli'
-	brotli "-kf$brotli_compression_level" "$out"
+	for ext in ${compression_filter:-html css js svg ico atom}; do
+		[ "${out##*.}" = "$ext" ] || continue
+		clevel="${brotli_compression_level:-Z}"
+		dbg "$out; level: $clevel" 'brotli'
+		brotli "-kf$clevel" "$out"
+		return
+	done
 }
diff --git a/mod/compression/gzip b/mod/compression/gzip
--- a/mod/compression/gzip
+++ b/mod/compression/gzip
@@ -1,14 +1,21 @@
 #!/bin/sh
-# gzip compress website files
+# gzip compresses website files
+#
+# PARAMS
+# $compression_filter list with extensions that should be compressed
+# $gzip_compression_level compression level
 if ! command -v gzip >/dev/null 2>&1; then
-	warn 'could not find gzip' 'gzip'
+	err 'could not find gzip binary' 'gzip'
 	return
 fi
 
-hook 9 'hook_gzip'
+hook 'hook_gzip'
 hook_gzip() {
-	gzip_compression_level="${gzip_compression_level:-9}"
-	echo "${out##*.}" | grep -Eq "^(${compression_filter:-html|css|js|svg|ico|atom})$" || return
-	debug "compressing $out; level: $gzip_compression_level" 'gzip'
-	gzip "-kf$gzip_compression_level" "$out"
+	for ext in ${compression_filter:-html css js svg ico atom}; do
+		[ "${out##*.}" = "$ext" ] || continue
+		clevel="${gzip_compression_level:-9}"
+		dbg "$out; level: $clevel" 'gzip'
+		gzip "-kf$gzip_compression_level" "$out"
+		return
+	done
 }
diff --git a/mod/minify b/mod/minify
--- a/mod/minify
+++ b/mod/minify
@@ -1,13 +1,20 @@
 #!/bin/sh
 # minify website files
+#
+# PARAMS
+# $minify_filter list with extensions that should be minified
+# $minify_flags additional minify flags
 if ! command -v minify >/dev/null 2>&1; then
-	err 'could not find minify binary; download: github.com/tdewolff/minify' 'minify'
+	err "could not find minify binary; download: github.com/tdewolff/minify" 'minify'
 	exit
 fi
 
-hook 8 'hook_minify'
-hook_minify(){
-	echo "${out##*.}" | grep -Eq "^(${minify_filter:-html|css|js|json|svg|xml})$" || return
-	debug "minifying $out" 'minify'
-	minify "$out" --output "$out" $minify_flags
+hook 'hook_minify'
+hook_minify() {
+	for ext in ${minify_filter:-html css js svg xml json}; do
+		[ "${out##*.}" = "$ext" ] || continue
+		dbg "$out" 'minify'
+		minify "$out" --output "$out" $minify_flags
+		return
+	done
 }
